# Generated by Django 3.0.5 on 2020-05-02 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(default=datetime.datetime.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize_list_app.Branch')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize_list_app.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='PrizeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_list_file', models.FileField(default=False, upload_to='')),
                ('date_submitted', models.DateField(verbose_name=datetime.date.today)),
                ('date_valid_to', models.DateField(default=datetime.date.today)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='prize_list_app.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrizeListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('prize', models.FloatField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize_list_app.Branch')),
                ('prize_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_list_item', to='prize_list_app.PrizeList')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_name', to='prize_list_app.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='prizelist',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='prize_list_app.Shop'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize_list_app.Branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize_list_app.PrizeListItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize_list_app.Order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize_list_app.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize_list_app.Shop'),
        ),
        migrations.AddField(
            model_name='branch',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize_list_app.Shop'),
        ),
    ]
