# Generated by Django 3.0.5 on 2020-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizelist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
