# Generated by Django 3.0.5 on 2020-05-11 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize_list_app', '0002_prizelist_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizelist',
            name='date_submitted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
